baseURL = 'https://dora.dev/'
languageCode = 'en-us'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[markup.goldmark.renderer]
unsafe= true

[params]
    Keywords = "DevOps, Lead time, Deploy frequency, Change fail rate, MTTR, Time to restore, metrics, DORA"
    Description = "DevOps Research and Assessment (DORA) is a long running research program that seeks to understand the capabilities that drive software delivery and operations performance. DORA helps teams apply those capabilities, leading to better organizational performance."

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[[cascade]]
  [cascade._target]
    path = "**/README.md"
  [cascade._build]
    render = "never"
    list = "never"

[languages]
  [languages.en]
    contentDir = 'content'
    disabled = false
    languageCode = 'en-EN'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'DevOps Research and Assessment'
    weight = 1
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'Français'
    title = 'DevOps Research and Assessment'
    weight = 2
